"""Immutable models for forecast-aware counterfactual interdiction.

Core Design Invariants:
-----------------------
1. Explicit OBSERVED vs. FORECAST Distinction:
   - OBSERVED: Ground-truth real TransactionEvent ingested into the canonical
     ledger from banking feeds/APIs.
   - FORECAST: Hypothetical, simulation-only edge generated solely for in-memory
     counterfactual scenario evaluation.
   A forecast event must NEVER be persisted as a canonical real TransactionEvent.

2. Integer Minor-Unit Arithmetic:
   - All money values use exact integer minor units (paise for INR).
   - No floating-point money amounts.

3. Complete Uncertainty Transparency:
   - Exposes prediction probabilities, scenario weights, forecast horizon,
     best-case, expected-case, and worst-case metrics.
   - Explicitly flags "insufficient_evidence" when prediction is unavailable.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum, unique
import hashlib
from typing import Sequence

from backend.app.counterfactual.models import (
    CounterfactualResult,
    InterventionType,
    SourceInterceptionDetail,
)
from contracts.account import AccountReference
from contracts.enums import (
    EventOrigin,
    TransactionChannel,
    TransactionStatus,
)
from contracts.transaction import TransactionEvent


@unique
class ForecastStatus(StrEnum):
    """Operational status of the next-hop forecast generation."""

    READY = "ready"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"
    NO_CANDIDATE_PATHS = "no_candidate_paths"


@dataclass(frozen=True, slots=True)
class ForecastTransactionEvent:
    """Simulation-only synthetic event representing a predicted future movement.

    IMPORTANT DISTINCTION:
    - This is a FORECAST EVENT, not observed transaction truth.
    - A forecast event must never be persisted as a canonical real TransactionEvent.
    - It preserves the predicted destination, source account, predicted amount,
      relative ordering, probability, and parent prediction/path relationship.
    """

    event_id: str
    transaction_id: str
    sender_account_id: str
    receiver_account_id: str
    amount_minor_units: int
    currency: str
    occurred_at: datetime
    probability: float
    path_id: str
    hop_index: int
    parent_prediction_id: str | None = None

    def to_simulation_event(self) -> TransactionEvent:
        """Create a temporary in-memory TransactionEvent for simulation graph ingestion.

        NOTE: This is strictly ephemeral for graph replay within CounterfactualSimulator
        and is NEVER written to the database or canonical event stream.
        """
        return TransactionEvent(
            event_id=self.event_id,
            transaction_id=self.transaction_id,
            sender=AccountReference(account_id=self.sender_account_id),
            receiver=AccountReference(account_id=self.receiver_account_id),
            amount_minor_units=self.amount_minor_units,
            currency=self.currency,
            occurred_at=self.occurred_at,
            observed_at=self.occurred_at,
            status=TransactionStatus.COMPLETED,
            channel=TransactionChannel.UPI,
            origin=EventOrigin.SYNTHETIC,
        )


@dataclass(frozen=True, slots=True)
class ForecastHop:
    """A single predicted hop in a plausible trajectory."""

    from_account_id: str
    to_account_id: str
    amount_minor_units: int
    probability: float
    occurred_at: datetime
    candidate_signals: dict[str, float] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class ForecastPath:
    """A bounded, plausible future transaction sequence generated by beam search."""

    path_id: str
    source_account_id: str
    hops: tuple[ForecastHop, ...]
    cumulative_probability: float
    accounts_sequence: tuple[str, ...]

    @property
    def hop_count(self) -> int:
        return len(self.hops)

    @property
    def destination_account_id(self) -> str:
        return self.accounts_sequence[-1] if self.accounts_sequence else self.source_account_id


@dataclass(frozen=True, slots=True)
class ScenarioEvaluationDetail:
    """Evaluation breakdown for one candidate intervention within a single future world."""

    scenario_id: str
    scenario_weight: float
    path_probability: float
    path_account_ids: tuple[str, ...]
    counterfactual_result: CounterfactualResult
    is_feasible: bool


@dataclass(frozen=True, slots=True)
class ForecastAwareCounterfactualResult(CounterfactualResult):
    """Counterfactual result extended with multi-future probability and robustness metrics.

    Conforms to the CounterfactualResult contract so existing optimizers and
    evaluators can consume it transparently, while exposing comprehensive
    robustness metrics:
    - Expected illicit recovery across futures
    - Worst-case illicit recovery
    - Expected legitimate impact
    - Worst-case legitimate impact
    - Feasibility / constraint satisfaction probability
    """

    forecast_status: str = ForecastStatus.READY.value
    futures_evaluated_count: int = 0
    forecast_horizon: int = 0
    prediction_probabilities: tuple[float, ...] = ()
    forecast_confidence: float | None = None
    expected_illicit_interception: int = 0
    worst_case_illicit_interception: int = 0
    best_case_illicit_interception: int = 0
    expected_legitimate_impact: int = 0
    worst_case_legitimate_impact: int = 0
    best_case_legitimate_impact: int = 0
    expected_affected_accounts: int = 0
    expected_affected_edges: int = 0
    constraint_satisfaction_probability: float = 0.0
    per_future_details: tuple[ScenarioEvaluationDetail, ...] = ()
